[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.microservices"

[environments.production.deploy]
startCommand = "sh -c npm run auth-service & npm run points-service & npm run main-service"