ARG NODE_VERSION=20.12.0

FROM node:${NODE_VERSION}-alpine

# Use production node environment by default.
ENV NODE_ENV production

WORKDIR /app

COPY ./MicroServices/package.json ./MicroServices/package-lock.json ./

RUN npm install

COPY . /app

# Run the application as a non-root user.
USER node

# Expose the port that the application listens on.
EXPOSE 8080

# Run the application.
CMD ["sh", "-c", "npm run auth-service & npm run points-service & npm run main-service"]